import Head from "next/head";
import PraticaOne from "@/componentes/pratica-1";
import Aleatorio from "@/componentes/pratica-2"
import Change from "@/componentes/pratica-3"

export default function Home() {
  return (
    <>
      <Head>
        <title>State hook</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PraticaOne />
      <Aleatorio />
      <Change />
    </>
  );
}
